# Generated by Django 6.1.1 on 2026-09-17 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.TextField()),
                ('title', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('record_type_raw', models.TextField(blank=True)),
                ('year', models.TextField(blank=True)),
                ('language', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('model_response', models.JSONField(blank=True, null=True)),
                ('model_status', models.TextField(default='pending')),
                ('model_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filename', models.TextField(blank=True)),
                ('status', models.TextField(default='processing')),
                ('error', models.TextField(blank=True)),
                ('handsort', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_level', models.TextField(blank=True)),
                ('signal_score', models.IntegerField(blank=True, null=True)),
                ('detail', models.JSONField(default=dict)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='web.record')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='web.run'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField()),
                ('value', models.JSONField(blank=True, null=True)),
                ('status', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='web.record')),
            ],
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('run', 'record_id'), name='record_unique_per_run'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('record', 'field'), name='tag_unique_per_record'),
        ),
    ]
