# Generated by Django 6.1.1 on 2026-09-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='review_yaml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='rubric_yaml',
            field=models.TextField(blank=True),
        ),
    ]
