# Generated by Django 6.1.1 on 2026-09-18 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_run_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rubric_yaml', models.TextField()),
                ('review_yaml', models.TextField()),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
